package com.enniu.loan.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class InterestPenaltyLogCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table interest_penalty_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table interest_penalty_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table interest_penalty_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_penalty_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public InterestPenaltyLogCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_penalty_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_penalty_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_penalty_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_penalty_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_penalty_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_penalty_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_penalty_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_penalty_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_penalty_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_penalty_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table interest_penalty_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andLoanOrderIdIsNull() {
            addCriterion("loan_order_id is null");
            return (Criteria) this;
        }

        public Criteria andLoanOrderIdIsNotNull() {
            addCriterion("loan_order_id is not null");
            return (Criteria) this;
        }

        public Criteria andLoanOrderIdEqualTo(Integer value) {
            addCriterion("loan_order_id =", value, "loanOrderId");
            return (Criteria) this;
        }

        public Criteria andLoanOrderIdNotEqualTo(Integer value) {
            addCriterion("loan_order_id <>", value, "loanOrderId");
            return (Criteria) this;
        }

        public Criteria andLoanOrderIdGreaterThan(Integer value) {
            addCriterion("loan_order_id >", value, "loanOrderId");
            return (Criteria) this;
        }

        public Criteria andLoanOrderIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("loan_order_id >=", value, "loanOrderId");
            return (Criteria) this;
        }

        public Criteria andLoanOrderIdLessThan(Integer value) {
            addCriterion("loan_order_id <", value, "loanOrderId");
            return (Criteria) this;
        }

        public Criteria andLoanOrderIdLessThanOrEqualTo(Integer value) {
            addCriterion("loan_order_id <=", value, "loanOrderId");
            return (Criteria) this;
        }

        public Criteria andLoanOrderIdIn(List<Integer> values) {
            addCriterion("loan_order_id in", values, "loanOrderId");
            return (Criteria) this;
        }

        public Criteria andLoanOrderIdNotIn(List<Integer> values) {
            addCriterion("loan_order_id not in", values, "loanOrderId");
            return (Criteria) this;
        }

        public Criteria andLoanOrderIdBetween(Integer value1, Integer value2) {
            addCriterion("loan_order_id between", value1, value2, "loanOrderId");
            return (Criteria) this;
        }

        public Criteria andLoanOrderIdNotBetween(Integer value1, Integer value2) {
            addCriterion("loan_order_id not between", value1, value2, "loanOrderId");
            return (Criteria) this;
        }

        public Criteria andRepaymentScheduleIdIsNull() {
            addCriterion("repayment_schedule_id is null");
            return (Criteria) this;
        }

        public Criteria andRepaymentScheduleIdIsNotNull() {
            addCriterion("repayment_schedule_id is not null");
            return (Criteria) this;
        }

        public Criteria andRepaymentScheduleIdEqualTo(Integer value) {
            addCriterion("repayment_schedule_id =", value, "repaymentScheduleId");
            return (Criteria) this;
        }

        public Criteria andRepaymentScheduleIdNotEqualTo(Integer value) {
            addCriterion("repayment_schedule_id <>", value, "repaymentScheduleId");
            return (Criteria) this;
        }

        public Criteria andRepaymentScheduleIdGreaterThan(Integer value) {
            addCriterion("repayment_schedule_id >", value, "repaymentScheduleId");
            return (Criteria) this;
        }

        public Criteria andRepaymentScheduleIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("repayment_schedule_id >=", value, "repaymentScheduleId");
            return (Criteria) this;
        }

        public Criteria andRepaymentScheduleIdLessThan(Integer value) {
            addCriterion("repayment_schedule_id <", value, "repaymentScheduleId");
            return (Criteria) this;
        }

        public Criteria andRepaymentScheduleIdLessThanOrEqualTo(Integer value) {
            addCriterion("repayment_schedule_id <=", value, "repaymentScheduleId");
            return (Criteria) this;
        }

        public Criteria andRepaymentScheduleIdIn(List<Integer> values) {
            addCriterion("repayment_schedule_id in", values, "repaymentScheduleId");
            return (Criteria) this;
        }

        public Criteria andRepaymentScheduleIdNotIn(List<Integer> values) {
            addCriterion("repayment_schedule_id not in", values, "repaymentScheduleId");
            return (Criteria) this;
        }

        public Criteria andRepaymentScheduleIdBetween(Integer value1, Integer value2) {
            addCriterion("repayment_schedule_id between", value1, value2, "repaymentScheduleId");
            return (Criteria) this;
        }

        public Criteria andRepaymentScheduleIdNotBetween(Integer value1, Integer value2) {
            addCriterion("repayment_schedule_id not between", value1, value2, "repaymentScheduleId");
            return (Criteria) this;
        }

        public Criteria andPenaltyAmountIsNull() {
            addCriterion("penalty_amount is null");
            return (Criteria) this;
        }

        public Criteria andPenaltyAmountIsNotNull() {
            addCriterion("penalty_amount is not null");
            return (Criteria) this;
        }

        public Criteria andPenaltyAmountEqualTo(Long value) {
            addCriterion("penalty_amount =", value, "penaltyAmount");
            return (Criteria) this;
        }

        public Criteria andPenaltyAmountNotEqualTo(Long value) {
            addCriterion("penalty_amount <>", value, "penaltyAmount");
            return (Criteria) this;
        }

        public Criteria andPenaltyAmountGreaterThan(Long value) {
            addCriterion("penalty_amount >", value, "penaltyAmount");
            return (Criteria) this;
        }

        public Criteria andPenaltyAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("penalty_amount >=", value, "penaltyAmount");
            return (Criteria) this;
        }

        public Criteria andPenaltyAmountLessThan(Long value) {
            addCriterion("penalty_amount <", value, "penaltyAmount");
            return (Criteria) this;
        }

        public Criteria andPenaltyAmountLessThanOrEqualTo(Long value) {
            addCriterion("penalty_amount <=", value, "penaltyAmount");
            return (Criteria) this;
        }

        public Criteria andPenaltyAmountIn(List<Long> values) {
            addCriterion("penalty_amount in", values, "penaltyAmount");
            return (Criteria) this;
        }

        public Criteria andPenaltyAmountNotIn(List<Long> values) {
            addCriterion("penalty_amount not in", values, "penaltyAmount");
            return (Criteria) this;
        }

        public Criteria andPenaltyAmountBetween(Long value1, Long value2) {
            addCriterion("penalty_amount between", value1, value2, "penaltyAmount");
            return (Criteria) this;
        }

        public Criteria andPenaltyAmountNotBetween(Long value1, Long value2) {
            addCriterion("penalty_amount not between", value1, value2, "penaltyAmount");
            return (Criteria) this;
        }

        public Criteria andPenaltyTypeIsNull() {
            addCriterion("penalty_type is null");
            return (Criteria) this;
        }

        public Criteria andPenaltyTypeIsNotNull() {
            addCriterion("penalty_type is not null");
            return (Criteria) this;
        }

        public Criteria andPenaltyTypeEqualTo(Byte value) {
            addCriterion("penalty_type =", value, "penaltyType");
            return (Criteria) this;
        }

        public Criteria andPenaltyTypeNotEqualTo(Byte value) {
            addCriterion("penalty_type <>", value, "penaltyType");
            return (Criteria) this;
        }

        public Criteria andPenaltyTypeGreaterThan(Byte value) {
            addCriterion("penalty_type >", value, "penaltyType");
            return (Criteria) this;
        }

        public Criteria andPenaltyTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("penalty_type >=", value, "penaltyType");
            return (Criteria) this;
        }

        public Criteria andPenaltyTypeLessThan(Byte value) {
            addCriterion("penalty_type <", value, "penaltyType");
            return (Criteria) this;
        }

        public Criteria andPenaltyTypeLessThanOrEqualTo(Byte value) {
            addCriterion("penalty_type <=", value, "penaltyType");
            return (Criteria) this;
        }

        public Criteria andPenaltyTypeIn(List<Byte> values) {
            addCriterion("penalty_type in", values, "penaltyType");
            return (Criteria) this;
        }

        public Criteria andPenaltyTypeNotIn(List<Byte> values) {
            addCriterion("penalty_type not in", values, "penaltyType");
            return (Criteria) this;
        }

        public Criteria andPenaltyTypeBetween(Byte value1, Byte value2) {
            addCriterion("penalty_type between", value1, value2, "penaltyType");
            return (Criteria) this;
        }

        public Criteria andPenaltyTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("penalty_type not between", value1, value2, "penaltyType");
            return (Criteria) this;
        }

        public Criteria andCreateAtIsNull() {
            addCriterion("create_at is null");
            return (Criteria) this;
        }

        public Criteria andCreateAtIsNotNull() {
            addCriterion("create_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreateAtEqualTo(Date value) {
            addCriterion("create_at =", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotEqualTo(Date value) {
            addCriterion("create_at <>", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtGreaterThan(Date value) {
            addCriterion("create_at >", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtGreaterThanOrEqualTo(Date value) {
            addCriterion("create_at >=", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtLessThan(Date value) {
            addCriterion("create_at <", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtLessThanOrEqualTo(Date value) {
            addCriterion("create_at <=", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtIn(List<Date> values) {
            addCriterion("create_at in", values, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotIn(List<Date> values) {
            addCriterion("create_at not in", values, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtBetween(Date value1, Date value2) {
            addCriterion("create_at between", value1, value2, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotBetween(Date value1, Date value2) {
            addCriterion("create_at not between", value1, value2, "createAt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table interest_penalty_log
     *
     * @mbggenerated do_not_delete_during_merge Wed Oct 01 11:26:25 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table interest_penalty_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}