package com.enniu.loan.domain;

import java.util.Date;

public class InterestPenaltyLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interest_penalty_log.id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interest_penalty_log.user_id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interest_penalty_log.loan_order_id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Integer loanOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interest_penalty_log.repayment_schedule_id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Integer repaymentScheduleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interest_penalty_log.penalty_amount
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Long penaltyAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interest_penalty_log.penalty_type
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Byte penaltyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interest_penalty_log.create_at
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Date createAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interest_penalty_log.id
     *
     * @return the value of interest_penalty_log.id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interest_penalty_log.id
     *
     * @param id the value for interest_penalty_log.id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interest_penalty_log.user_id
     *
     * @return the value of interest_penalty_log.user_id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interest_penalty_log.user_id
     *
     * @param userId the value for interest_penalty_log.user_id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interest_penalty_log.loan_order_id
     *
     * @return the value of interest_penalty_log.loan_order_id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Integer getLoanOrderId() {
        return loanOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interest_penalty_log.loan_order_id
     *
     * @param loanOrderId the value for interest_penalty_log.loan_order_id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setLoanOrderId(Integer loanOrderId) {
        this.loanOrderId = loanOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interest_penalty_log.repayment_schedule_id
     *
     * @return the value of interest_penalty_log.repayment_schedule_id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Integer getRepaymentScheduleId() {
        return repaymentScheduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interest_penalty_log.repayment_schedule_id
     *
     * @param repaymentScheduleId the value for interest_penalty_log.repayment_schedule_id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setRepaymentScheduleId(Integer repaymentScheduleId) {
        this.repaymentScheduleId = repaymentScheduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interest_penalty_log.penalty_amount
     *
     * @return the value of interest_penalty_log.penalty_amount
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Long getPenaltyAmount() {
        return penaltyAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interest_penalty_log.penalty_amount
     *
     * @param penaltyAmount the value for interest_penalty_log.penalty_amount
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setPenaltyAmount(Long penaltyAmount) {
        this.penaltyAmount = penaltyAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interest_penalty_log.penalty_type
     *
     * @return the value of interest_penalty_log.penalty_type
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Byte getPenaltyType() {
        return penaltyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interest_penalty_log.penalty_type
     *
     * @param penaltyType the value for interest_penalty_log.penalty_type
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setPenaltyType(Byte penaltyType) {
        this.penaltyType = penaltyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interest_penalty_log.create_at
     *
     * @return the value of interest_penalty_log.create_at
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interest_penalty_log.create_at
     *
     * @param createAt the value for interest_penalty_log.create_at
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }
}