package com.enniu.loan.domain;

import java.util.Date;

public class LoanOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order.id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order.user_id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order.credit_card
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Long creditCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order.deposit_card
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Long depositCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order.amount
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Long amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order.status
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order.overdue
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Short overdue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order.created_at
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order.due_at
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Date dueAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order.id
     *
     * @return the value of loan_order.id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order.id
     *
     * @param id the value for loan_order.id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order.user_id
     *
     * @return the value of loan_order.user_id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order.user_id
     *
     * @param userId the value for loan_order.user_id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order.credit_card
     *
     * @return the value of loan_order.credit_card
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Long getCreditCard() {
        return creditCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order.credit_card
     *
     * @param creditCard the value for loan_order.credit_card
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setCreditCard(Long creditCard) {
        this.creditCard = creditCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order.deposit_card
     *
     * @return the value of loan_order.deposit_card
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Long getDepositCard() {
        return depositCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order.deposit_card
     *
     * @param depositCard the value for loan_order.deposit_card
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setDepositCard(Long depositCard) {
        this.depositCard = depositCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order.amount
     *
     * @return the value of loan_order.amount
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order.amount
     *
     * @param amount the value for loan_order.amount
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order.status
     *
     * @return the value of loan_order.status
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order.status
     *
     * @param status the value for loan_order.status
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order.overdue
     *
     * @return the value of loan_order.overdue
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Short getOverdue() {
        return overdue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order.overdue
     *
     * @param overdue the value for loan_order.overdue
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setOverdue(Short overdue) {
        this.overdue = overdue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order.created_at
     *
     * @return the value of loan_order.created_at
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order.created_at
     *
     * @param createdAt the value for loan_order.created_at
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order.due_at
     *
     * @return the value of loan_order.due_at
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Date getDueAt() {
        return dueAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order.due_at
     *
     * @param dueAt the value for loan_order.due_at
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setDueAt(Date dueAt) {
        this.dueAt = dueAt;
    }
}