package com.enniu.loan.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RepaymentScheduleCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table repayment_schedule
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table repayment_schedule
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table repayment_schedule
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_schedule
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public RepaymentScheduleCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_schedule
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_schedule
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_schedule
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_schedule
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_schedule
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_schedule
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_schedule
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_schedule
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_schedule
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_schedule
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table repayment_schedule
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andLoanOrderIdIsNull() {
            addCriterion("loan_order_id is null");
            return (Criteria) this;
        }

        public Criteria andLoanOrderIdIsNotNull() {
            addCriterion("loan_order_id is not null");
            return (Criteria) this;
        }

        public Criteria andLoanOrderIdEqualTo(Integer value) {
            addCriterion("loan_order_id =", value, "loanOrderId");
            return (Criteria) this;
        }

        public Criteria andLoanOrderIdNotEqualTo(Integer value) {
            addCriterion("loan_order_id <>", value, "loanOrderId");
            return (Criteria) this;
        }

        public Criteria andLoanOrderIdGreaterThan(Integer value) {
            addCriterion("loan_order_id >", value, "loanOrderId");
            return (Criteria) this;
        }

        public Criteria andLoanOrderIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("loan_order_id >=", value, "loanOrderId");
            return (Criteria) this;
        }

        public Criteria andLoanOrderIdLessThan(Integer value) {
            addCriterion("loan_order_id <", value, "loanOrderId");
            return (Criteria) this;
        }

        public Criteria andLoanOrderIdLessThanOrEqualTo(Integer value) {
            addCriterion("loan_order_id <=", value, "loanOrderId");
            return (Criteria) this;
        }

        public Criteria andLoanOrderIdIn(List<Integer> values) {
            addCriterion("loan_order_id in", values, "loanOrderId");
            return (Criteria) this;
        }

        public Criteria andLoanOrderIdNotIn(List<Integer> values) {
            addCriterion("loan_order_id not in", values, "loanOrderId");
            return (Criteria) this;
        }

        public Criteria andLoanOrderIdBetween(Integer value1, Integer value2) {
            addCriterion("loan_order_id between", value1, value2, "loanOrderId");
            return (Criteria) this;
        }

        public Criteria andLoanOrderIdNotBetween(Integer value1, Integer value2) {
            addCriterion("loan_order_id not between", value1, value2, "loanOrderId");
            return (Criteria) this;
        }

        public Criteria andPeriodIsNull() {
            addCriterion("period is null");
            return (Criteria) this;
        }

        public Criteria andPeriodIsNotNull() {
            addCriterion("period is not null");
            return (Criteria) this;
        }

        public Criteria andPeriodEqualTo(Byte value) {
            addCriterion("period =", value, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodNotEqualTo(Byte value) {
            addCriterion("period <>", value, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodGreaterThan(Byte value) {
            addCriterion("period >", value, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodGreaterThanOrEqualTo(Byte value) {
            addCriterion("period >=", value, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodLessThan(Byte value) {
            addCriterion("period <", value, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodLessThanOrEqualTo(Byte value) {
            addCriterion("period <=", value, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodIn(List<Byte> values) {
            addCriterion("period in", values, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodNotIn(List<Byte> values) {
            addCriterion("period not in", values, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodBetween(Byte value1, Byte value2) {
            addCriterion("period between", value1, value2, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodNotBetween(Byte value1, Byte value2) {
            addCriterion("period not between", value1, value2, "period");
            return (Criteria) this;
        }

        public Criteria andStartAtIsNull() {
            addCriterion("start_at is null");
            return (Criteria) this;
        }

        public Criteria andStartAtIsNotNull() {
            addCriterion("start_at is not null");
            return (Criteria) this;
        }

        public Criteria andStartAtEqualTo(Date value) {
            addCriterion("start_at =", value, "startAt");
            return (Criteria) this;
        }

        public Criteria andStartAtNotEqualTo(Date value) {
            addCriterion("start_at <>", value, "startAt");
            return (Criteria) this;
        }

        public Criteria andStartAtGreaterThan(Date value) {
            addCriterion("start_at >", value, "startAt");
            return (Criteria) this;
        }

        public Criteria andStartAtGreaterThanOrEqualTo(Date value) {
            addCriterion("start_at >=", value, "startAt");
            return (Criteria) this;
        }

        public Criteria andStartAtLessThan(Date value) {
            addCriterion("start_at <", value, "startAt");
            return (Criteria) this;
        }

        public Criteria andStartAtLessThanOrEqualTo(Date value) {
            addCriterion("start_at <=", value, "startAt");
            return (Criteria) this;
        }

        public Criteria andStartAtIn(List<Date> values) {
            addCriterion("start_at in", values, "startAt");
            return (Criteria) this;
        }

        public Criteria andStartAtNotIn(List<Date> values) {
            addCriterion("start_at not in", values, "startAt");
            return (Criteria) this;
        }

        public Criteria andStartAtBetween(Date value1, Date value2) {
            addCriterion("start_at between", value1, value2, "startAt");
            return (Criteria) this;
        }

        public Criteria andStartAtNotBetween(Date value1, Date value2) {
            addCriterion("start_at not between", value1, value2, "startAt");
            return (Criteria) this;
        }

        public Criteria andDueAtIsNull() {
            addCriterion("due_at is null");
            return (Criteria) this;
        }

        public Criteria andDueAtIsNotNull() {
            addCriterion("due_at is not null");
            return (Criteria) this;
        }

        public Criteria andDueAtEqualTo(Date value) {
            addCriterion("due_at =", value, "dueAt");
            return (Criteria) this;
        }

        public Criteria andDueAtNotEqualTo(Date value) {
            addCriterion("due_at <>", value, "dueAt");
            return (Criteria) this;
        }

        public Criteria andDueAtGreaterThan(Date value) {
            addCriterion("due_at >", value, "dueAt");
            return (Criteria) this;
        }

        public Criteria andDueAtGreaterThanOrEqualTo(Date value) {
            addCriterion("due_at >=", value, "dueAt");
            return (Criteria) this;
        }

        public Criteria andDueAtLessThan(Date value) {
            addCriterion("due_at <", value, "dueAt");
            return (Criteria) this;
        }

        public Criteria andDueAtLessThanOrEqualTo(Date value) {
            addCriterion("due_at <=", value, "dueAt");
            return (Criteria) this;
        }

        public Criteria andDueAtIn(List<Date> values) {
            addCriterion("due_at in", values, "dueAt");
            return (Criteria) this;
        }

        public Criteria andDueAtNotIn(List<Date> values) {
            addCriterion("due_at not in", values, "dueAt");
            return (Criteria) this;
        }

        public Criteria andDueAtBetween(Date value1, Date value2) {
            addCriterion("due_at between", value1, value2, "dueAt");
            return (Criteria) this;
        }

        public Criteria andDueAtNotBetween(Date value1, Date value2) {
            addCriterion("due_at not between", value1, value2, "dueAt");
            return (Criteria) this;
        }

        public Criteria andRepayAtIsNull() {
            addCriterion("repay_at is null");
            return (Criteria) this;
        }

        public Criteria andRepayAtIsNotNull() {
            addCriterion("repay_at is not null");
            return (Criteria) this;
        }

        public Criteria andRepayAtEqualTo(Date value) {
            addCriterion("repay_at =", value, "repayAt");
            return (Criteria) this;
        }

        public Criteria andRepayAtNotEqualTo(Date value) {
            addCriterion("repay_at <>", value, "repayAt");
            return (Criteria) this;
        }

        public Criteria andRepayAtGreaterThan(Date value) {
            addCriterion("repay_at >", value, "repayAt");
            return (Criteria) this;
        }

        public Criteria andRepayAtGreaterThanOrEqualTo(Date value) {
            addCriterion("repay_at >=", value, "repayAt");
            return (Criteria) this;
        }

        public Criteria andRepayAtLessThan(Date value) {
            addCriterion("repay_at <", value, "repayAt");
            return (Criteria) this;
        }

        public Criteria andRepayAtLessThanOrEqualTo(Date value) {
            addCriterion("repay_at <=", value, "repayAt");
            return (Criteria) this;
        }

        public Criteria andRepayAtIn(List<Date> values) {
            addCriterion("repay_at in", values, "repayAt");
            return (Criteria) this;
        }

        public Criteria andRepayAtNotIn(List<Date> values) {
            addCriterion("repay_at not in", values, "repayAt");
            return (Criteria) this;
        }

        public Criteria andRepayAtBetween(Date value1, Date value2) {
            addCriterion("repay_at between", value1, value2, "repayAt");
            return (Criteria) this;
        }

        public Criteria andRepayAtNotBetween(Date value1, Date value2) {
            addCriterion("repay_at not between", value1, value2, "repayAt");
            return (Criteria) this;
        }

        public Criteria andCapitalIsNull() {
            addCriterion("capital is null");
            return (Criteria) this;
        }

        public Criteria andCapitalIsNotNull() {
            addCriterion("capital is not null");
            return (Criteria) this;
        }

        public Criteria andCapitalEqualTo(Long value) {
            addCriterion("capital =", value, "capital");
            return (Criteria) this;
        }

        public Criteria andCapitalNotEqualTo(Long value) {
            addCriterion("capital <>", value, "capital");
            return (Criteria) this;
        }

        public Criteria andCapitalGreaterThan(Long value) {
            addCriterion("capital >", value, "capital");
            return (Criteria) this;
        }

        public Criteria andCapitalGreaterThanOrEqualTo(Long value) {
            addCriterion("capital >=", value, "capital");
            return (Criteria) this;
        }

        public Criteria andCapitalLessThan(Long value) {
            addCriterion("capital <", value, "capital");
            return (Criteria) this;
        }

        public Criteria andCapitalLessThanOrEqualTo(Long value) {
            addCriterion("capital <=", value, "capital");
            return (Criteria) this;
        }

        public Criteria andCapitalIn(List<Long> values) {
            addCriterion("capital in", values, "capital");
            return (Criteria) this;
        }

        public Criteria andCapitalNotIn(List<Long> values) {
            addCriterion("capital not in", values, "capital");
            return (Criteria) this;
        }

        public Criteria andCapitalBetween(Long value1, Long value2) {
            addCriterion("capital between", value1, value2, "capital");
            return (Criteria) this;
        }

        public Criteria andCapitalNotBetween(Long value1, Long value2) {
            addCriterion("capital not between", value1, value2, "capital");
            return (Criteria) this;
        }

        public Criteria andInterestIsNull() {
            addCriterion("interest is null");
            return (Criteria) this;
        }

        public Criteria andInterestIsNotNull() {
            addCriterion("interest is not null");
            return (Criteria) this;
        }

        public Criteria andInterestEqualTo(Long value) {
            addCriterion("interest =", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestNotEqualTo(Long value) {
            addCriterion("interest <>", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestGreaterThan(Long value) {
            addCriterion("interest >", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestGreaterThanOrEqualTo(Long value) {
            addCriterion("interest >=", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestLessThan(Long value) {
            addCriterion("interest <", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestLessThanOrEqualTo(Long value) {
            addCriterion("interest <=", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestIn(List<Long> values) {
            addCriterion("interest in", values, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestNotIn(List<Long> values) {
            addCriterion("interest not in", values, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestBetween(Long value1, Long value2) {
            addCriterion("interest between", value1, value2, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestNotBetween(Long value1, Long value2) {
            addCriterion("interest not between", value1, value2, "interest");
            return (Criteria) this;
        }

        public Criteria andGratuityIsNull() {
            addCriterion("gratuity is null");
            return (Criteria) this;
        }

        public Criteria andGratuityIsNotNull() {
            addCriterion("gratuity is not null");
            return (Criteria) this;
        }

        public Criteria andGratuityEqualTo(Long value) {
            addCriterion("gratuity =", value, "gratuity");
            return (Criteria) this;
        }

        public Criteria andGratuityNotEqualTo(Long value) {
            addCriterion("gratuity <>", value, "gratuity");
            return (Criteria) this;
        }

        public Criteria andGratuityGreaterThan(Long value) {
            addCriterion("gratuity >", value, "gratuity");
            return (Criteria) this;
        }

        public Criteria andGratuityGreaterThanOrEqualTo(Long value) {
            addCriterion("gratuity >=", value, "gratuity");
            return (Criteria) this;
        }

        public Criteria andGratuityLessThan(Long value) {
            addCriterion("gratuity <", value, "gratuity");
            return (Criteria) this;
        }

        public Criteria andGratuityLessThanOrEqualTo(Long value) {
            addCriterion("gratuity <=", value, "gratuity");
            return (Criteria) this;
        }

        public Criteria andGratuityIn(List<Long> values) {
            addCriterion("gratuity in", values, "gratuity");
            return (Criteria) this;
        }

        public Criteria andGratuityNotIn(List<Long> values) {
            addCriterion("gratuity not in", values, "gratuity");
            return (Criteria) this;
        }

        public Criteria andGratuityBetween(Long value1, Long value2) {
            addCriterion("gratuity between", value1, value2, "gratuity");
            return (Criteria) this;
        }

        public Criteria andGratuityNotBetween(Long value1, Long value2) {
            addCriterion("gratuity not between", value1, value2, "gratuity");
            return (Criteria) this;
        }

        public Criteria andPenaltyIsNull() {
            addCriterion("penalty is null");
            return (Criteria) this;
        }

        public Criteria andPenaltyIsNotNull() {
            addCriterion("penalty is not null");
            return (Criteria) this;
        }

        public Criteria andPenaltyEqualTo(Long value) {
            addCriterion("penalty =", value, "penalty");
            return (Criteria) this;
        }

        public Criteria andPenaltyNotEqualTo(Long value) {
            addCriterion("penalty <>", value, "penalty");
            return (Criteria) this;
        }

        public Criteria andPenaltyGreaterThan(Long value) {
            addCriterion("penalty >", value, "penalty");
            return (Criteria) this;
        }

        public Criteria andPenaltyGreaterThanOrEqualTo(Long value) {
            addCriterion("penalty >=", value, "penalty");
            return (Criteria) this;
        }

        public Criteria andPenaltyLessThan(Long value) {
            addCriterion("penalty <", value, "penalty");
            return (Criteria) this;
        }

        public Criteria andPenaltyLessThanOrEqualTo(Long value) {
            addCriterion("penalty <=", value, "penalty");
            return (Criteria) this;
        }

        public Criteria andPenaltyIn(List<Long> values) {
            addCriterion("penalty in", values, "penalty");
            return (Criteria) this;
        }

        public Criteria andPenaltyNotIn(List<Long> values) {
            addCriterion("penalty not in", values, "penalty");
            return (Criteria) this;
        }

        public Criteria andPenaltyBetween(Long value1, Long value2) {
            addCriterion("penalty between", value1, value2, "penalty");
            return (Criteria) this;
        }

        public Criteria andPenaltyNotBetween(Long value1, Long value2) {
            addCriterion("penalty not between", value1, value2, "penalty");
            return (Criteria) this;
        }

        public Criteria andRepaidCapitalIsNull() {
            addCriterion("repaid_capital is null");
            return (Criteria) this;
        }

        public Criteria andRepaidCapitalIsNotNull() {
            addCriterion("repaid_capital is not null");
            return (Criteria) this;
        }

        public Criteria andRepaidCapitalEqualTo(Long value) {
            addCriterion("repaid_capital =", value, "repaidCapital");
            return (Criteria) this;
        }

        public Criteria andRepaidCapitalNotEqualTo(Long value) {
            addCriterion("repaid_capital <>", value, "repaidCapital");
            return (Criteria) this;
        }

        public Criteria andRepaidCapitalGreaterThan(Long value) {
            addCriterion("repaid_capital >", value, "repaidCapital");
            return (Criteria) this;
        }

        public Criteria andRepaidCapitalGreaterThanOrEqualTo(Long value) {
            addCriterion("repaid_capital >=", value, "repaidCapital");
            return (Criteria) this;
        }

        public Criteria andRepaidCapitalLessThan(Long value) {
            addCriterion("repaid_capital <", value, "repaidCapital");
            return (Criteria) this;
        }

        public Criteria andRepaidCapitalLessThanOrEqualTo(Long value) {
            addCriterion("repaid_capital <=", value, "repaidCapital");
            return (Criteria) this;
        }

        public Criteria andRepaidCapitalIn(List<Long> values) {
            addCriterion("repaid_capital in", values, "repaidCapital");
            return (Criteria) this;
        }

        public Criteria andRepaidCapitalNotIn(List<Long> values) {
            addCriterion("repaid_capital not in", values, "repaidCapital");
            return (Criteria) this;
        }

        public Criteria andRepaidCapitalBetween(Long value1, Long value2) {
            addCriterion("repaid_capital between", value1, value2, "repaidCapital");
            return (Criteria) this;
        }

        public Criteria andRepaidCapitalNotBetween(Long value1, Long value2) {
            addCriterion("repaid_capital not between", value1, value2, "repaidCapital");
            return (Criteria) this;
        }

        public Criteria andRepaidInterestIsNull() {
            addCriterion("repaid_interest is null");
            return (Criteria) this;
        }

        public Criteria andRepaidInterestIsNotNull() {
            addCriterion("repaid_interest is not null");
            return (Criteria) this;
        }

        public Criteria andRepaidInterestEqualTo(Long value) {
            addCriterion("repaid_interest =", value, "repaidInterest");
            return (Criteria) this;
        }

        public Criteria andRepaidInterestNotEqualTo(Long value) {
            addCriterion("repaid_interest <>", value, "repaidInterest");
            return (Criteria) this;
        }

        public Criteria andRepaidInterestGreaterThan(Long value) {
            addCriterion("repaid_interest >", value, "repaidInterest");
            return (Criteria) this;
        }

        public Criteria andRepaidInterestGreaterThanOrEqualTo(Long value) {
            addCriterion("repaid_interest >=", value, "repaidInterest");
            return (Criteria) this;
        }

        public Criteria andRepaidInterestLessThan(Long value) {
            addCriterion("repaid_interest <", value, "repaidInterest");
            return (Criteria) this;
        }

        public Criteria andRepaidInterestLessThanOrEqualTo(Long value) {
            addCriterion("repaid_interest <=", value, "repaidInterest");
            return (Criteria) this;
        }

        public Criteria andRepaidInterestIn(List<Long> values) {
            addCriterion("repaid_interest in", values, "repaidInterest");
            return (Criteria) this;
        }

        public Criteria andRepaidInterestNotIn(List<Long> values) {
            addCriterion("repaid_interest not in", values, "repaidInterest");
            return (Criteria) this;
        }

        public Criteria andRepaidInterestBetween(Long value1, Long value2) {
            addCriterion("repaid_interest between", value1, value2, "repaidInterest");
            return (Criteria) this;
        }

        public Criteria andRepaidInterestNotBetween(Long value1, Long value2) {
            addCriterion("repaid_interest not between", value1, value2, "repaidInterest");
            return (Criteria) this;
        }

        public Criteria andRepaidGratuityIsNull() {
            addCriterion("repaid_gratuity is null");
            return (Criteria) this;
        }

        public Criteria andRepaidGratuityIsNotNull() {
            addCriterion("repaid_gratuity is not null");
            return (Criteria) this;
        }

        public Criteria andRepaidGratuityEqualTo(Long value) {
            addCriterion("repaid_gratuity =", value, "repaidGratuity");
            return (Criteria) this;
        }

        public Criteria andRepaidGratuityNotEqualTo(Long value) {
            addCriterion("repaid_gratuity <>", value, "repaidGratuity");
            return (Criteria) this;
        }

        public Criteria andRepaidGratuityGreaterThan(Long value) {
            addCriterion("repaid_gratuity >", value, "repaidGratuity");
            return (Criteria) this;
        }

        public Criteria andRepaidGratuityGreaterThanOrEqualTo(Long value) {
            addCriterion("repaid_gratuity >=", value, "repaidGratuity");
            return (Criteria) this;
        }

        public Criteria andRepaidGratuityLessThan(Long value) {
            addCriterion("repaid_gratuity <", value, "repaidGratuity");
            return (Criteria) this;
        }

        public Criteria andRepaidGratuityLessThanOrEqualTo(Long value) {
            addCriterion("repaid_gratuity <=", value, "repaidGratuity");
            return (Criteria) this;
        }

        public Criteria andRepaidGratuityIn(List<Long> values) {
            addCriterion("repaid_gratuity in", values, "repaidGratuity");
            return (Criteria) this;
        }

        public Criteria andRepaidGratuityNotIn(List<Long> values) {
            addCriterion("repaid_gratuity not in", values, "repaidGratuity");
            return (Criteria) this;
        }

        public Criteria andRepaidGratuityBetween(Long value1, Long value2) {
            addCriterion("repaid_gratuity between", value1, value2, "repaidGratuity");
            return (Criteria) this;
        }

        public Criteria andRepaidGratuityNotBetween(Long value1, Long value2) {
            addCriterion("repaid_gratuity not between", value1, value2, "repaidGratuity");
            return (Criteria) this;
        }

        public Criteria andRepaidPenaltyIsNull() {
            addCriterion("repaid_penalty is null");
            return (Criteria) this;
        }

        public Criteria andRepaidPenaltyIsNotNull() {
            addCriterion("repaid_penalty is not null");
            return (Criteria) this;
        }

        public Criteria andRepaidPenaltyEqualTo(Long value) {
            addCriterion("repaid_penalty =", value, "repaidPenalty");
            return (Criteria) this;
        }

        public Criteria andRepaidPenaltyNotEqualTo(Long value) {
            addCriterion("repaid_penalty <>", value, "repaidPenalty");
            return (Criteria) this;
        }

        public Criteria andRepaidPenaltyGreaterThan(Long value) {
            addCriterion("repaid_penalty >", value, "repaidPenalty");
            return (Criteria) this;
        }

        public Criteria andRepaidPenaltyGreaterThanOrEqualTo(Long value) {
            addCriterion("repaid_penalty >=", value, "repaidPenalty");
            return (Criteria) this;
        }

        public Criteria andRepaidPenaltyLessThan(Long value) {
            addCriterion("repaid_penalty <", value, "repaidPenalty");
            return (Criteria) this;
        }

        public Criteria andRepaidPenaltyLessThanOrEqualTo(Long value) {
            addCriterion("repaid_penalty <=", value, "repaidPenalty");
            return (Criteria) this;
        }

        public Criteria andRepaidPenaltyIn(List<Long> values) {
            addCriterion("repaid_penalty in", values, "repaidPenalty");
            return (Criteria) this;
        }

        public Criteria andRepaidPenaltyNotIn(List<Long> values) {
            addCriterion("repaid_penalty not in", values, "repaidPenalty");
            return (Criteria) this;
        }

        public Criteria andRepaidPenaltyBetween(Long value1, Long value2) {
            addCriterion("repaid_penalty between", value1, value2, "repaidPenalty");
            return (Criteria) this;
        }

        public Criteria andRepaidPenaltyNotBetween(Long value1, Long value2) {
            addCriterion("repaid_penalty not between", value1, value2, "repaidPenalty");
            return (Criteria) this;
        }

        public Criteria andExemptionIsNull() {
            addCriterion("exemption is null");
            return (Criteria) this;
        }

        public Criteria andExemptionIsNotNull() {
            addCriterion("exemption is not null");
            return (Criteria) this;
        }

        public Criteria andExemptionEqualTo(Long value) {
            addCriterion("exemption =", value, "exemption");
            return (Criteria) this;
        }

        public Criteria andExemptionNotEqualTo(Long value) {
            addCriterion("exemption <>", value, "exemption");
            return (Criteria) this;
        }

        public Criteria andExemptionGreaterThan(Long value) {
            addCriterion("exemption >", value, "exemption");
            return (Criteria) this;
        }

        public Criteria andExemptionGreaterThanOrEqualTo(Long value) {
            addCriterion("exemption >=", value, "exemption");
            return (Criteria) this;
        }

        public Criteria andExemptionLessThan(Long value) {
            addCriterion("exemption <", value, "exemption");
            return (Criteria) this;
        }

        public Criteria andExemptionLessThanOrEqualTo(Long value) {
            addCriterion("exemption <=", value, "exemption");
            return (Criteria) this;
        }

        public Criteria andExemptionIn(List<Long> values) {
            addCriterion("exemption in", values, "exemption");
            return (Criteria) this;
        }

        public Criteria andExemptionNotIn(List<Long> values) {
            addCriterion("exemption not in", values, "exemption");
            return (Criteria) this;
        }

        public Criteria andExemptionBetween(Long value1, Long value2) {
            addCriterion("exemption between", value1, value2, "exemption");
            return (Criteria) this;
        }

        public Criteria andExemptionNotBetween(Long value1, Long value2) {
            addCriterion("exemption not between", value1, value2, "exemption");
            return (Criteria) this;
        }

        public Criteria andIsClearIsNull() {
            addCriterion("is_clear is null");
            return (Criteria) this;
        }

        public Criteria andIsClearIsNotNull() {
            addCriterion("is_clear is not null");
            return (Criteria) this;
        }

        public Criteria andIsClearEqualTo(Byte value) {
            addCriterion("is_clear =", value, "isClear");
            return (Criteria) this;
        }

        public Criteria andIsClearNotEqualTo(Byte value) {
            addCriterion("is_clear <>", value, "isClear");
            return (Criteria) this;
        }

        public Criteria andIsClearGreaterThan(Byte value) {
            addCriterion("is_clear >", value, "isClear");
            return (Criteria) this;
        }

        public Criteria andIsClearGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_clear >=", value, "isClear");
            return (Criteria) this;
        }

        public Criteria andIsClearLessThan(Byte value) {
            addCriterion("is_clear <", value, "isClear");
            return (Criteria) this;
        }

        public Criteria andIsClearLessThanOrEqualTo(Byte value) {
            addCriterion("is_clear <=", value, "isClear");
            return (Criteria) this;
        }

        public Criteria andIsClearIn(List<Byte> values) {
            addCriterion("is_clear in", values, "isClear");
            return (Criteria) this;
        }

        public Criteria andIsClearNotIn(List<Byte> values) {
            addCriterion("is_clear not in", values, "isClear");
            return (Criteria) this;
        }

        public Criteria andIsClearBetween(Byte value1, Byte value2) {
            addCriterion("is_clear between", value1, value2, "isClear");
            return (Criteria) this;
        }

        public Criteria andIsClearNotBetween(Byte value1, Byte value2) {
            addCriterion("is_clear not between", value1, value2, "isClear");
            return (Criteria) this;
        }

        public Criteria andOverdueIsNull() {
            addCriterion("overdue is null");
            return (Criteria) this;
        }

        public Criteria andOverdueIsNotNull() {
            addCriterion("overdue is not null");
            return (Criteria) this;
        }

        public Criteria andOverdueEqualTo(Short value) {
            addCriterion("overdue =", value, "overdue");
            return (Criteria) this;
        }

        public Criteria andOverdueNotEqualTo(Short value) {
            addCriterion("overdue <>", value, "overdue");
            return (Criteria) this;
        }

        public Criteria andOverdueGreaterThan(Short value) {
            addCriterion("overdue >", value, "overdue");
            return (Criteria) this;
        }

        public Criteria andOverdueGreaterThanOrEqualTo(Short value) {
            addCriterion("overdue >=", value, "overdue");
            return (Criteria) this;
        }

        public Criteria andOverdueLessThan(Short value) {
            addCriterion("overdue <", value, "overdue");
            return (Criteria) this;
        }

        public Criteria andOverdueLessThanOrEqualTo(Short value) {
            addCriterion("overdue <=", value, "overdue");
            return (Criteria) this;
        }

        public Criteria andOverdueIn(List<Short> values) {
            addCriterion("overdue in", values, "overdue");
            return (Criteria) this;
        }

        public Criteria andOverdueNotIn(List<Short> values) {
            addCriterion("overdue not in", values, "overdue");
            return (Criteria) this;
        }

        public Criteria andOverdueBetween(Short value1, Short value2) {
            addCriterion("overdue between", value1, value2, "overdue");
            return (Criteria) this;
        }

        public Criteria andOverdueNotBetween(Short value1, Short value2) {
            addCriterion("overdue not between", value1, value2, "overdue");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andOperationIsNull() {
            addCriterion("operation is null");
            return (Criteria) this;
        }

        public Criteria andOperationIsNotNull() {
            addCriterion("operation is not null");
            return (Criteria) this;
        }

        public Criteria andOperationEqualTo(Byte value) {
            addCriterion("operation =", value, "operation");
            return (Criteria) this;
        }

        public Criteria andOperationNotEqualTo(Byte value) {
            addCriterion("operation <>", value, "operation");
            return (Criteria) this;
        }

        public Criteria andOperationGreaterThan(Byte value) {
            addCriterion("operation >", value, "operation");
            return (Criteria) this;
        }

        public Criteria andOperationGreaterThanOrEqualTo(Byte value) {
            addCriterion("operation >=", value, "operation");
            return (Criteria) this;
        }

        public Criteria andOperationLessThan(Byte value) {
            addCriterion("operation <", value, "operation");
            return (Criteria) this;
        }

        public Criteria andOperationLessThanOrEqualTo(Byte value) {
            addCriterion("operation <=", value, "operation");
            return (Criteria) this;
        }

        public Criteria andOperationIn(List<Byte> values) {
            addCriterion("operation in", values, "operation");
            return (Criteria) this;
        }

        public Criteria andOperationNotIn(List<Byte> values) {
            addCriterion("operation not in", values, "operation");
            return (Criteria) this;
        }

        public Criteria andOperationBetween(Byte value1, Byte value2) {
            addCriterion("operation between", value1, value2, "operation");
            return (Criteria) this;
        }

        public Criteria andOperationNotBetween(Byte value1, Byte value2) {
            addCriterion("operation not between", value1, value2, "operation");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table repayment_schedule
     *
     * @mbggenerated do_not_delete_during_merge Wed Oct 01 11:26:25 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table repayment_schedule
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}