package com.enniu.loan.domain;

import java.util.Date;

public class RepaymentLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_log.id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_log.repayment_schedule_id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Integer repaymentScheduleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_log.withhold_log_id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Integer withholdLogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_log.repaid_amount
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Long repaidAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_log.withhold_type
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Byte withholdType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_log.repaid_type
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Byte repaidType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_log.create_at
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Date createAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_log.id
     *
     * @return the value of repayment_log.id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_log.id
     *
     * @param id the value for repayment_log.id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_log.repayment_schedule_id
     *
     * @return the value of repayment_log.repayment_schedule_id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Integer getRepaymentScheduleId() {
        return repaymentScheduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_log.repayment_schedule_id
     *
     * @param repaymentScheduleId the value for repayment_log.repayment_schedule_id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setRepaymentScheduleId(Integer repaymentScheduleId) {
        this.repaymentScheduleId = repaymentScheduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_log.withhold_log_id
     *
     * @return the value of repayment_log.withhold_log_id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Integer getWithholdLogId() {
        return withholdLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_log.withhold_log_id
     *
     * @param withholdLogId the value for repayment_log.withhold_log_id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setWithholdLogId(Integer withholdLogId) {
        this.withholdLogId = withholdLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_log.repaid_amount
     *
     * @return the value of repayment_log.repaid_amount
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Long getRepaidAmount() {
        return repaidAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_log.repaid_amount
     *
     * @param repaidAmount the value for repayment_log.repaid_amount
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setRepaidAmount(Long repaidAmount) {
        this.repaidAmount = repaidAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_log.withhold_type
     *
     * @return the value of repayment_log.withhold_type
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Byte getWithholdType() {
        return withholdType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_log.withhold_type
     *
     * @param withholdType the value for repayment_log.withhold_type
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setWithholdType(Byte withholdType) {
        this.withholdType = withholdType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_log.repaid_type
     *
     * @return the value of repayment_log.repaid_type
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Byte getRepaidType() {
        return repaidType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_log.repaid_type
     *
     * @param repaidType the value for repayment_log.repaid_type
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setRepaidType(Byte repaidType) {
        this.repaidType = repaidType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_log.create_at
     *
     * @return the value of repayment_log.create_at
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_log.create_at
     *
     * @param createAt the value for repayment_log.create_at
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }
}