package com.enniu.loan.domain;

import java.util.Date;

public class RepaymentSchedule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_schedule.id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_schedule.loan_order_id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Integer loanOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_schedule.period
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Byte period;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_schedule.start_at
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Date startAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_schedule.due_at
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Date dueAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_schedule.repay_at
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Date repayAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_schedule.capital
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Long capital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_schedule.interest
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Long interest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_schedule.gratuity
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Long gratuity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_schedule.penalty
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Long penalty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_schedule.repaid_capital
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Long repaidCapital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_schedule.repaid_interest
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Long repaidInterest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_schedule.repaid_gratuity
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Long repaidGratuity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_schedule.repaid_penalty
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Long repaidPenalty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_schedule.exemption
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Long exemption;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_schedule.is_clear
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Byte isClear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_schedule.overdue
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Short overdue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_schedule.status
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_schedule.operation
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Byte operation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_schedule.id
     *
     * @return the value of repayment_schedule.id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_schedule.id
     *
     * @param id the value for repayment_schedule.id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_schedule.loan_order_id
     *
     * @return the value of repayment_schedule.loan_order_id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Integer getLoanOrderId() {
        return loanOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_schedule.loan_order_id
     *
     * @param loanOrderId the value for repayment_schedule.loan_order_id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setLoanOrderId(Integer loanOrderId) {
        this.loanOrderId = loanOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_schedule.period
     *
     * @return the value of repayment_schedule.period
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Byte getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_schedule.period
     *
     * @param period the value for repayment_schedule.period
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setPeriod(Byte period) {
        this.period = period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_schedule.start_at
     *
     * @return the value of repayment_schedule.start_at
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Date getStartAt() {
        return startAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_schedule.start_at
     *
     * @param startAt the value for repayment_schedule.start_at
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setStartAt(Date startAt) {
        this.startAt = startAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_schedule.due_at
     *
     * @return the value of repayment_schedule.due_at
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Date getDueAt() {
        return dueAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_schedule.due_at
     *
     * @param dueAt the value for repayment_schedule.due_at
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setDueAt(Date dueAt) {
        this.dueAt = dueAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_schedule.repay_at
     *
     * @return the value of repayment_schedule.repay_at
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Date getRepayAt() {
        return repayAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_schedule.repay_at
     *
     * @param repayAt the value for repayment_schedule.repay_at
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setRepayAt(Date repayAt) {
        this.repayAt = repayAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_schedule.capital
     *
     * @return the value of repayment_schedule.capital
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Long getCapital() {
        return capital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_schedule.capital
     *
     * @param capital the value for repayment_schedule.capital
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setCapital(Long capital) {
        this.capital = capital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_schedule.interest
     *
     * @return the value of repayment_schedule.interest
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Long getInterest() {
        return interest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_schedule.interest
     *
     * @param interest the value for repayment_schedule.interest
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setInterest(Long interest) {
        this.interest = interest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_schedule.gratuity
     *
     * @return the value of repayment_schedule.gratuity
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Long getGratuity() {
        return gratuity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_schedule.gratuity
     *
     * @param gratuity the value for repayment_schedule.gratuity
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setGratuity(Long gratuity) {
        this.gratuity = gratuity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_schedule.penalty
     *
     * @return the value of repayment_schedule.penalty
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Long getPenalty() {
        return penalty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_schedule.penalty
     *
     * @param penalty the value for repayment_schedule.penalty
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setPenalty(Long penalty) {
        this.penalty = penalty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_schedule.repaid_capital
     *
     * @return the value of repayment_schedule.repaid_capital
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Long getRepaidCapital() {
        return repaidCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_schedule.repaid_capital
     *
     * @param repaidCapital the value for repayment_schedule.repaid_capital
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setRepaidCapital(Long repaidCapital) {
        this.repaidCapital = repaidCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_schedule.repaid_interest
     *
     * @return the value of repayment_schedule.repaid_interest
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Long getRepaidInterest() {
        return repaidInterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_schedule.repaid_interest
     *
     * @param repaidInterest the value for repayment_schedule.repaid_interest
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setRepaidInterest(Long repaidInterest) {
        this.repaidInterest = repaidInterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_schedule.repaid_gratuity
     *
     * @return the value of repayment_schedule.repaid_gratuity
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Long getRepaidGratuity() {
        return repaidGratuity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_schedule.repaid_gratuity
     *
     * @param repaidGratuity the value for repayment_schedule.repaid_gratuity
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setRepaidGratuity(Long repaidGratuity) {
        this.repaidGratuity = repaidGratuity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_schedule.repaid_penalty
     *
     * @return the value of repayment_schedule.repaid_penalty
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Long getRepaidPenalty() {
        return repaidPenalty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_schedule.repaid_penalty
     *
     * @param repaidPenalty the value for repayment_schedule.repaid_penalty
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setRepaidPenalty(Long repaidPenalty) {
        this.repaidPenalty = repaidPenalty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_schedule.exemption
     *
     * @return the value of repayment_schedule.exemption
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Long getExemption() {
        return exemption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_schedule.exemption
     *
     * @param exemption the value for repayment_schedule.exemption
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setExemption(Long exemption) {
        this.exemption = exemption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_schedule.is_clear
     *
     * @return the value of repayment_schedule.is_clear
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Byte getIsClear() {
        return isClear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_schedule.is_clear
     *
     * @param isClear the value for repayment_schedule.is_clear
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setIsClear(Byte isClear) {
        this.isClear = isClear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_schedule.overdue
     *
     * @return the value of repayment_schedule.overdue
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Short getOverdue() {
        return overdue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_schedule.overdue
     *
     * @param overdue the value for repayment_schedule.overdue
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setOverdue(Short overdue) {
        this.overdue = overdue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_schedule.status
     *
     * @return the value of repayment_schedule.status
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_schedule.status
     *
     * @param status the value for repayment_schedule.status
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_schedule.operation
     *
     * @return the value of repayment_schedule.operation
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Byte getOperation() {
        return operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_schedule.operation
     *
     * @param operation the value for repayment_schedule.operation
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setOperation(Byte operation) {
        this.operation = operation;
    }
}