package com.enniu.loan.domain;

import java.util.Date;

public class WithholdLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withhold_log.id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withhold_log.loan_order_id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Integer loanOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withhold_log.repayment_schedule_id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Integer repaymentScheduleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withhold_log.withhold_order_id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Integer withholdOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withhold_log.amount
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Long amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withhold_log.result
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private String result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withhold_log.description
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withhold_log.created_at
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withhold_log.id
     *
     * @return the value of withhold_log.id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withhold_log.id
     *
     * @param id the value for withhold_log.id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withhold_log.loan_order_id
     *
     * @return the value of withhold_log.loan_order_id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Integer getLoanOrderId() {
        return loanOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withhold_log.loan_order_id
     *
     * @param loanOrderId the value for withhold_log.loan_order_id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setLoanOrderId(Integer loanOrderId) {
        this.loanOrderId = loanOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withhold_log.repayment_schedule_id
     *
     * @return the value of withhold_log.repayment_schedule_id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Integer getRepaymentScheduleId() {
        return repaymentScheduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withhold_log.repayment_schedule_id
     *
     * @param repaymentScheduleId the value for withhold_log.repayment_schedule_id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setRepaymentScheduleId(Integer repaymentScheduleId) {
        this.repaymentScheduleId = repaymentScheduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withhold_log.withhold_order_id
     *
     * @return the value of withhold_log.withhold_order_id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Integer getWithholdOrderId() {
        return withholdOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withhold_log.withhold_order_id
     *
     * @param withholdOrderId the value for withhold_log.withhold_order_id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setWithholdOrderId(Integer withholdOrderId) {
        this.withholdOrderId = withholdOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withhold_log.amount
     *
     * @return the value of withhold_log.amount
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withhold_log.amount
     *
     * @param amount the value for withhold_log.amount
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withhold_log.result
     *
     * @return the value of withhold_log.result
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withhold_log.result
     *
     * @param result the value for withhold_log.result
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withhold_log.description
     *
     * @return the value of withhold_log.description
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withhold_log.description
     *
     * @param description the value for withhold_log.description
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withhold_log.created_at
     *
     * @return the value of withhold_log.created_at
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withhold_log.created_at
     *
     * @param createdAt the value for withhold_log.created_at
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}