package com.enniu.loan.domain;

import java.util.Date;

public class WithholdOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withhold_order.id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withhold_order.loan_order_id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Integer loanOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withhold_order.order_id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withhold_order.deposit_card
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Long depositCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withhold_order.temp_card
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Long tempCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withhold_order.created_at
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withhold_order.id
     *
     * @return the value of withhold_order.id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withhold_order.id
     *
     * @param id the value for withhold_order.id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withhold_order.loan_order_id
     *
     * @return the value of withhold_order.loan_order_id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Integer getLoanOrderId() {
        return loanOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withhold_order.loan_order_id
     *
     * @param loanOrderId the value for withhold_order.loan_order_id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setLoanOrderId(Integer loanOrderId) {
        this.loanOrderId = loanOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withhold_order.order_id
     *
     * @return the value of withhold_order.order_id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withhold_order.order_id
     *
     * @param orderId the value for withhold_order.order_id
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withhold_order.deposit_card
     *
     * @return the value of withhold_order.deposit_card
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Long getDepositCard() {
        return depositCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withhold_order.deposit_card
     *
     * @param depositCard the value for withhold_order.deposit_card
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setDepositCard(Long depositCard) {
        this.depositCard = depositCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withhold_order.temp_card
     *
     * @return the value of withhold_order.temp_card
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Long getTempCard() {
        return tempCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withhold_order.temp_card
     *
     * @param tempCard the value for withhold_order.temp_card
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setTempCard(Long tempCard) {
        this.tempCard = tempCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withhold_order.created_at
     *
     * @return the value of withhold_order.created_at
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withhold_order.created_at
     *
     * @param createdAt the value for withhold_order.created_at
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}