package com.enniu.loan.persistence;

import com.enniu.loan.domain.InterestPenaltyLog;
import com.enniu.loan.domain.InterestPenaltyLogCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InterestPenaltyLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_penalty_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int countByCriteria(InterestPenaltyLogCriteria criteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_penalty_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int deleteByCriteria(InterestPenaltyLogCriteria criteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_penalty_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_penalty_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int insert(InterestPenaltyLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_penalty_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int insertSelective(InterestPenaltyLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_penalty_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    List<InterestPenaltyLog> selectByCriteria(InterestPenaltyLogCriteria criteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_penalty_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    InterestPenaltyLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_penalty_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int updateByCriteriaSelective(@Param("record") InterestPenaltyLog record, @Param("criteria") InterestPenaltyLogCriteria criteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_penalty_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int updateByCriteria(@Param("record") InterestPenaltyLog record, @Param("criteria") InterestPenaltyLogCriteria criteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_penalty_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int updateByPrimaryKeySelective(InterestPenaltyLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_penalty_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int updateByPrimaryKey(InterestPenaltyLog record);
}