package com.enniu.loan.persistence;

import com.enniu.loan.domain.LoanOrder;
import com.enniu.loan.domain.LoanOrderCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LoanOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_order
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int countByExample(LoanOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_order
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int deleteByExample(LoanOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_order
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_order
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int insert(LoanOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_order
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int insertSelective(LoanOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_order
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    List<LoanOrder> selectByExample(LoanOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_order
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    LoanOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_order
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int updateByExampleSelective(@Param("record") LoanOrder record, @Param("example") LoanOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_order
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int updateByExample(@Param("record") LoanOrder record, @Param("example") LoanOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_order
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int updateByPrimaryKeySelective(LoanOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_order
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int updateByPrimaryKey(LoanOrder record);
}