package com.enniu.loan.persistence;

import com.enniu.loan.domain.RepaymentSchedule;
import com.enniu.loan.domain.RepaymentScheduleCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RepaymentScheduleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_schedule
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int countByExample(RepaymentScheduleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_schedule
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int deleteByExample(RepaymentScheduleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_schedule
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_schedule
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int insert(RepaymentSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_schedule
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int insertSelective(RepaymentSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_schedule
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    List<RepaymentSchedule> selectByExample(RepaymentScheduleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_schedule
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    RepaymentSchedule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_schedule
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int updateByExampleSelective(@Param("record") RepaymentSchedule record, @Param("example") RepaymentScheduleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_schedule
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int updateByExample(@Param("record") RepaymentSchedule record, @Param("example") RepaymentScheduleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_schedule
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int updateByPrimaryKeySelective(RepaymentSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_schedule
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int updateByPrimaryKey(RepaymentSchedule record);
}