package com.enniu.loan.persistence;

import com.enniu.loan.domain.RepaymentLog;
import com.enniu.loan.domain.RepaymentLogCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RepaymentLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int countByCriteria(RepaymentLogCriteria criteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int deleteByCriteria(RepaymentLogCriteria criteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int insert(RepaymentLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int insertSelective(RepaymentLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    List<RepaymentLog> selectByCriteria(RepaymentLogCriteria criteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    RepaymentLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int updateByCriteriaSelective(@Param("record") RepaymentLog record, @Param("criteria") RepaymentLogCriteria criteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int updateByCriteria(@Param("record") RepaymentLog record, @Param("criteria") RepaymentLogCriteria criteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int updateByPrimaryKeySelective(RepaymentLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int updateByPrimaryKey(RepaymentLog record);
}