package com.enniu.loan.persistence;

import com.enniu.loan.domain.WithholdLog;
import com.enniu.loan.domain.WithholdLogCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WithholdLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withhold_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int countByCriteria(WithholdLogCriteria criteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withhold_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int deleteByCriteria(WithholdLogCriteria criteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withhold_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withhold_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int insert(WithholdLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withhold_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int insertSelective(WithholdLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withhold_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    List<WithholdLog> selectByCriteria(WithholdLogCriteria criteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withhold_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    WithholdLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withhold_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int updateByCriteriaSelective(@Param("record") WithholdLog record, @Param("criteria") WithholdLogCriteria criteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withhold_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int updateByCriteria(@Param("record") WithholdLog record, @Param("criteria") WithholdLogCriteria criteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withhold_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int updateByPrimaryKeySelective(WithholdLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withhold_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int updateByPrimaryKey(WithholdLog record);
}