package com.enniu.loan.persistence;

import com.enniu.loan.domain.WithholdOrder;
import com.enniu.loan.domain.WithholdOrderCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WithholdOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withhold_order
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int countByExample(WithholdOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withhold_order
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int deleteByExample(WithholdOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withhold_order
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withhold_order
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int insert(WithholdOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withhold_order
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int insertSelective(WithholdOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withhold_order
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    List<WithholdOrder> selectByExample(WithholdOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withhold_order
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    WithholdOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withhold_order
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int updateByExampleSelective(@Param("record") WithholdOrder record, @Param("example") WithholdOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withhold_order
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int updateByExample(@Param("record") WithholdOrder record, @Param("example") WithholdOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withhold_order
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int updateByPrimaryKeySelective(WithholdOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withhold_order
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int updateByPrimaryKey(WithholdOrder record);
}