package com.enniu.loan.persistence;

import com.enniu.loan.domain.WithholdLog;
import com.enniu.loan.domain.WithholdLogCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WithholdLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withhold_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int countByExample(WithholdLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withhold_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int deleteByExample(WithholdLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withhold_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withhold_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int insert(WithholdLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withhold_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int insertSelective(WithholdLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withhold_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    List<WithholdLog> selectByExample(WithholdLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withhold_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    WithholdLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withhold_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int updateByExampleSelective(@Param("record") WithholdLog record, @Param("example") WithholdLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withhold_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int updateByExample(@Param("record") WithholdLog record, @Param("example") WithholdLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withhold_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int updateByPrimaryKeySelective(WithholdLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withhold_log
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int updateByPrimaryKey(WithholdLog record);
}