package com.enniu.loan.persistence;

import com.enniu.loan.domain.WithholdOrder;
import com.enniu.loan.domain.WithholdOrderCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WithholdOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withhold_order
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int countByCriteria(WithholdOrderCriteria criteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withhold_order
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int deleteByCriteria(WithholdOrderCriteria criteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withhold_order
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withhold_order
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int insert(WithholdOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withhold_order
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int insertSelective(WithholdOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withhold_order
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    List<WithholdOrder> selectByCriteria(WithholdOrderCriteria criteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withhold_order
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    WithholdOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withhold_order
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int updateByCriteriaSelective(@Param("record") WithholdOrder record, @Param("criteria") WithholdOrderCriteria criteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withhold_order
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int updateByCriteria(@Param("record") WithholdOrder record, @Param("criteria") WithholdOrderCriteria criteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withhold_order
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int updateByPrimaryKeySelective(WithholdOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withhold_order
     *
     * @mbggenerated Wed Oct 01 11:26:25 CST 2014
     */
    int updateByPrimaryKey(WithholdOrder record);
}